//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicacionLibreria2018.WSPedidos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/WSPedido.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DniCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoCli {
            get {
                return this.CorreoCliField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoCliField, value) != true)) {
                    this.CorreoCliField = value;
                    this.RaisePropertyChanged("CorreoCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DniCli {
            get {
                return this.DniCliField;
            }
            set {
                if ((this.DniCliField.Equals(value) != true)) {
                    this.DniCliField = value;
                    this.RaisePropertyChanged("DniCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPed {
            get {
                return this.FechaPedField;
            }
            set {
                if ((this.FechaPedField.Equals(value) != true)) {
                    this.FechaPedField = value;
                    this.RaisePropertyChanged("FechaPed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCli {
            get {
                return this.NombreCliField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCliField, value) != true)) {
                    this.NombreCliField = value;
                    this.RaisePropertyChanged("NombreCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFile {
            get {
                return this.RutaFileField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFileField, value) != true)) {
                    this.RutaFileField = value;
                    this.RaisePropertyChanged("RutaFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPedidos.IPedidos")]
    public interface IPedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/CrearPedido", ReplyAction="http://tempuri.org/IPedidos/CrearPedidoResponse")]
        WebAplicacionLibreria2018.WSPedidos.Pedido CrearPedido(WebAplicacionLibreria2018.WSPedidos.Pedido pedidoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/CrearPedido", ReplyAction="http://tempuri.org/IPedidos/CrearPedidoResponse")]
        System.Threading.Tasks.Task<WebAplicacionLibreria2018.WSPedidos.Pedido> CrearPedidoAsync(WebAplicacionLibreria2018.WSPedidos.Pedido pedidoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/ObtenerPedido", ReplyAction="http://tempuri.org/IPedidos/ObtenerPedidoResponse")]
        WebAplicacionLibreria2018.WSPedidos.Pedido ObtenerPedido(int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidos/ObtenerPedido", ReplyAction="http://tempuri.org/IPedidos/ObtenerPedidoResponse")]
        System.Threading.Tasks.Task<WebAplicacionLibreria2018.WSPedidos.Pedido> ObtenerPedidoAsync(int dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosChannel : WebAplicacionLibreria2018.WSPedidos.IPedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosClient : System.ServiceModel.ClientBase<WebAplicacionLibreria2018.WSPedidos.IPedidos>, WebAplicacionLibreria2018.WSPedidos.IPedidos {
        
        public PedidosClient() {
        }
        
        public PedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAplicacionLibreria2018.WSPedidos.Pedido CrearPedido(WebAplicacionLibreria2018.WSPedidos.Pedido pedidoACrear) {
            return base.Channel.CrearPedido(pedidoACrear);
        }
        
        public System.Threading.Tasks.Task<WebAplicacionLibreria2018.WSPedidos.Pedido> CrearPedidoAsync(WebAplicacionLibreria2018.WSPedidos.Pedido pedidoACrear) {
            return base.Channel.CrearPedidoAsync(pedidoACrear);
        }
        
        public WebAplicacionLibreria2018.WSPedidos.Pedido ObtenerPedido(int dni) {
            return base.Channel.ObtenerPedido(dni);
        }
        
        public System.Threading.Tasks.Task<WebAplicacionLibreria2018.WSPedidos.Pedido> ObtenerPedidoAsync(int dni) {
            return base.Channel.ObtenerPedidoAsync(dni);
        }
    }
}
